#!/usr/bin/env bash
cd SNIPER
echo -e "\e[33m          _____ _ _ ___________ ___________ \e[0m"
echo -e "\e[33m          / ___ | \ | | _ _ | ___ \ ___ | ___ \
echo -e "\e[33m          \ `-. | \ | | | | | | _ / / | __ | | _ / /\e[0m"
echo -e "\e[33m           `-. \. `| | | | __ / | __ || /\e[0m"
echo -e "\e[33m          / \ __ / / | \ | _ | | _ | | | | ___ | | \ \\e[0m"
echo -e "\e[33m          \ ____ / \ _ | \ _ / \ ___ / \ _ | \ ____ / \ _ | \ _ |\e[0m"
while(true) do
lua start.lua 
done
                                 
                                 